### ISSUE TITLE
Re-configure host update

### ISSUE THREAD

**Issue by mzsanford** [natekspencer/hacs-vestaboard#5]
My Vestaboard recently rebooted and came up on a new IP address. I'm working out why the static IP did not work but in the meantime I would like to reconfigure hacs-vestaboard and update the host value. Reconfigure only provides options for coilor and quiet hours. How can the host and/or API key be updated?

**Comment by natekspencer** [comment]
Right now there isn't a good way. If you have access to the file system, you can find the config entry file under `config` -> `.storage` -> `core.config_entries` and manually edit the host. Or you can also delete and then re-add the integration with the new host. I'll have to work on a fix to adjust the host entry during a re-configure.

I'm curious, as my static IP recently stopped working and I noticed the reported mac address was different, can you verify what firmware you are on from the Vestaboard app? Also, are you able to ping `vestaboard.local` on your network and get a response? (I'm not able to)

**Comment by mzsanford** [comment]
Thanks for the config location, it wasn't easy to identify. I think something is afoot with a Vestaboard firmware update. A change of MAC would explain why the Google WiFi router didn't apply the static IP rule. I noticed the app shows 3 MAC addresses now and firmware v3.1.0. While resetting things I also noticed `vestaboard.local` stopped working as I was hoping to use that to avoid this issue going forward.

I ended up removing/re-adding the device, after which the `vestaboard.message` service worked but `notify.vestaboard` was still logging an unreachable host. I assumed it was using a cached host value so I took this opportunity to install the HA core update and reboot. Now none of it is working and the log (below) seems to indicate an HTTP/HTTPS mismatch somewhere. I'm hoping to revisit this again tonight and tomorrow to troubleshoot that some more. It's probably something outside of this extension but I wanted to include it in case you run into the same.

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 10:36:26 AM (16 occurrences)
Last logged: 10:45:12 AM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02\xa6\x01'
```
